export const FETCH_STOCKS_REQUEST = 'FETCH_STOCKS_REQUEST';
export const FETCH_STOCKS_SUCCESS = 'FETCH_STOCKS_SUCCESS';
export const FETCH_STOCKS_FAILURE = 'FETCH_STOCKS_FAILURE';
export const SET_CURRENT_PAGE_NEXT = 'SET_CURRENT_PAGE_NEXT';
export const SET_CURRENT_PAGE_PERV = 'SET_CURRENT_PAGE_PERV';